// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEso-2OAQGe6qThIu2QjGKb_6ZEcwLC-c',
    appId: '1:646401074445:web:1a485dcf293f051b273c44',
    messagingSenderId: '646401074445',
    projectId: 'hotplate-4b9e6',
    authDomain: 'hotplate-4b9e6.firebaseapp.com',
    databaseURL: 'https://hotplate-4b9e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotplate-4b9e6.firebasestorage.app',
    measurementId: 'G-Q69JTBP8HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRLqBW6tJ9_yZVKfff-tjF9JvOMo-qiEU',
    appId: '1:646401074445:android:b0691c6da309ddf9273c44',
    messagingSenderId: '646401074445',
    projectId: 'hotplate-4b9e6',
    databaseURL: 'https://hotplate-4b9e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotplate-4b9e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jC0zQsEgd_gdXv09ZNRW-Bh4LXDFZpw',
    appId: '1:646401074445:ios:2868bbb7c3dcdfda273c44',
    messagingSenderId: '646401074445',
    projectId: 'hotplate-4b9e6',
    databaseURL: 'https://hotplate-4b9e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotplate-4b9e6.firebasestorage.app',
    iosBundleId: 'com.example.hotplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5jC0zQsEgd_gdXv09ZNRW-Bh4LXDFZpw',
    appId: '1:646401074445:ios:2868bbb7c3dcdfda273c44',
    messagingSenderId: '646401074445',
    projectId: 'hotplate-4b9e6',
    databaseURL: 'https://hotplate-4b9e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotplate-4b9e6.firebasestorage.app',
    iosBundleId: 'com.example.hotplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEso-2OAQGe6qThIu2QjGKb_6ZEcwLC-c',
    appId: '1:646401074445:web:a82a5050945b8bc0273c44',
    messagingSenderId: '646401074445',
    projectId: 'hotplate-4b9e6',
    authDomain: 'hotplate-4b9e6.firebaseapp.com',
    databaseURL: 'https://hotplate-4b9e6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hotplate-4b9e6.firebasestorage.app',
    measurementId: 'G-H9F61LXNT9',
  );

}